#!/usr/bin/env php
<?php
ob_clean();
putenv("@root=" . __DIR__);
putenv("@config=" . __DIR__ . '/dev/config/config.php');
putenv("@di=" . __DIR__ . '/dev/config/di.php');
include __DIR__ . '/dev/app.php';